title: Refugio Económico
description: Economía pública para el bien común.
url: "https://policy.refugioeconomico.mx"
baseurl: ""

email: socapal@outlook.com

substack_rec: "https://refugioeconomico.substack.com/"
substack_pc: "https://puntocomun.substack.com/"
github_profile: "https://github.com/socapal"
notion_publications: "https://puntocomun.notion.site/publicaciones?v=cb87345890a74f3dbd7ad27c71b673eb&pvs=74"

header_pages:
  - policy_briefs.md
  - working_papers.md
  - resources/resources.md
  - about.md

exclude:
  - scripts
  - tests
  - _archive

collections:
  radar:
    output: true
    permalink: /resources/vivienda/radar/:name/

defaults:
  - scope:
      path: ""
      type: radar
    values:
      layout: radar
